# SI Data Generator Native App Configuration
# This file contains application-specific configuration for the Native App

app_name: "SI Data Generator"
app_version: "1.0"
description: "Intelligent demo data generator for Snowflake Cortex services"

# Default configuration values
default_settings:
  max_records: 1000
  min_records: 100
  enable_cortex_search: true
  enable_semantic_views: true

# Supported demo types
demo_types:
  - e-commerce
  - healthcare
  - financial_services
  - retail
  - manufacturing
  - technology
